# Generated by Django 5.1.1 on 2024-09-09 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMBExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exDate', models.DateField()),
                ('exCriteria1', models.BooleanField(default=False)),
                ('exCriteria2', models.BooleanField(default=False)),
                ('exCriteria3', models.BooleanField(default=False)),
                ('exCriteria4', models.BooleanField(default=False)),
                ('exCriteria5', models.BooleanField(default=False)),
                ('exCriteria6', models.BooleanField(default=False)),
                ('score', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
            ],
        ),
    ]
