# Generated by Django 5.1.1 on 2024-09-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_remove_smbexercise_exdate_remove_smbexercise_score_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smbexercise',
            table=None,
        ),
    ]
