# Generated by Django 5.1.1 on 2024-09-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_smbexercise_exdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='smbexercise',
            name='exPlayer',
            field=models.CharField(default='John Doe', max_length=20),
        ),
    ]
