# Generated by Django 5.1.1 on 2024-09-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_smbexercise_explayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smbexercise',
            name='exPlayer',
            field=models.CharField(default='John_Doe', max_length=20),
        ),
    ]