# Generated by Django 5.1.1 on 2024-09-30 02:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_delete_student_alter_smbexercise_exdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exName', models.CharField(max_length=255)),
                ('exCriteriaDesc1', models.CharField(max_length=255)),
                ('exCriteriaDesc2', models.CharField(max_length=255)),
                ('exCriteriaDesc3', models.CharField(max_length=255)),
                ('exCriteriaDesc4', models.CharField(max_length=255)),
                ('exCriteriaDesc5', models.CharField(max_length=255)),
                ('exCriteriaDesc6', models.CharField(max_length=255)),
                ('exDifficulty', models.IntegerField()),
                ('exType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exPlayerName', models.CharField(max_length=20)),
                ('exCriteria1', models.BooleanField(default=False)),
                ('exCriteria2', models.BooleanField(default=False)),
                ('exCriteria3', models.BooleanField(default=False)),
                ('exCriteria4', models.BooleanField(default=False)),
                ('exCriteria5', models.BooleanField(default=False)),
                ('exCriteria6', models.BooleanField(default=False)),
                ('exDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('exName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.exinfo')),
            ],
        ),
    ]
