# Generated by Django 5.1.1 on 2024-11-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0010_exinfo_exlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exlog',
            name='exComment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
